import type { NodeData, EdgeData } from "./canvas-geometry";

/**
 * Generate a README.md / ARCHITECTURE.md from the visual canvas.
 * Uses Groq API if configured, otherwise generates a structured template.
 */
export async function generateReadme(
  nodes: NodeData[],
  edges: EdgeData[],
  projectName: string,
  workspace: "app" | "erd",
): Promise<string> {
  const appNodes = nodes.filter((n) => n.workspace === "app" || workspace === "app");
  const erdNodes = nodes.filter((n) => n.workspace === "erd" || workspace === "erd");

  const lines: string[] = [];
  lines.push(`# ${projectName} — Architecture Documentation`);
  lines.push("");
  lines.push("> Auto-generated from the visual architecture canvas.");
  lines.push("");

  if (appNodes.length > 0) {
    lines.push("## Application Flow");
    lines.push("");
    lines.push("The system consists of the following components:");
    lines.push("");
    for (const n of appNodes) {
      const icon = shapeToIcon(n.shape);
      lines.push(`- **${icon} ${n.label}**${n.sub ? ` — ${n.sub}` : ""}`);
    }
    lines.push("");

    // Connections
    const incoming = new Map<string, string[]>();
    const outgoing = new Map<string, string[]>();
    for (const e of edges) {
      if (!outgoing.has(e.from)) outgoing.set(e.from, []);
      if (!incoming.has(e.to)) incoming.set(e.to, []);
      const fromNode = nodes.find((n) => n.id === e.from);
      const toNode = nodes.find((n) => n.id === e.to);
      if (fromNode && toNode) {
        outgoing.get(e.from)!.push(toNode.label);
        incoming.get(e.to)!.push(fromNode.label);
      }
    }
    lines.push("### Data Flow");
    lines.push("");
    for (const n of appNodes) {
      const outs = outgoing.get(n.id) ?? [];
      const ins = incoming.get(n.id) ?? [];
      if (outs.length > 0 || ins.length > 0) {
        lines.push(`- **${n.label}**:`);
        if (ins.length > 0) lines.push(`  - Receives from: ${ins.join(", ")}`);
        if (outs.length > 0) lines.push(`  - Sends to: ${outs.join(", ")}`);
      }
    }
    lines.push("");
  }

  if (erdNodes.length > 0) {
    lines.push("## Database Schema");
    lines.push("");
    for (const n of erdNodes) {
      if (n.tableName) {
        lines.push(`### ${n.tableName}`);
        lines.push("");
        if (n.columns && n.columns.length > 0) {
          lines.push("| Column | Type | Constraints |");
          lines.push("|--------|------|------------|");
          for (const col of n.columns) {
            const constraints = [
              col.isPK ? "PK" : "",
              col.isFK ? `FK → ${col.references ?? ""}` : "",
              col.nullable === false ? "NOT NULL" : "",
            ].filter(Boolean).join(", ");
            lines.push(`| ${col.name} | ${col.type} | ${constraints} |`);
          }
          lines.push("");
        }
      }
    }
  }

  // Orphaned nodes detection
  const connectedIds = new Set<string>();
  for (const e of edges) { connectedIds.add(e.from); connectedIds.add(e.to); }
  const orphans = nodes.filter((n) => !connectedIds.has(n.id));
  if (orphans.length > 0) {
    lines.push("## ⚠️ Orphaned Components");
    lines.push("");
    lines.push("The following components have no connections and may need review:");
    lines.push("");
    for (const n of orphans) {
      lines.push(`- ${n.label}`);
    }
    lines.push("");
  }

  // Complexity metrics
  const totalNodes = nodes.length;
  const totalEdges = edges.length;
  const avgDepth = totalNodes > 0 ? (totalEdges / totalNodes).toFixed(2) : "0";
  lines.push("## Complexity Metrics");
  lines.push("");
  lines.push(`- **Total Components**: ${totalNodes}`);
  lines.push(`- **Total Connections**: ${totalEdges}`);
  lines.push(`- **Average Dependencies per Component**: ${avgDepth}`);
  lines.push(`- **Orphaned Components**: ${orphans.length}`);
  lines.push("");

  lines.push("---");
  lines.push("*Generated by the Architecture Visualizer*");

  return lines.join("\n");
}

function shapeToIcon(shape: string): string {
  const map: Record<string, string> = {
    rectangle: "[rect]", pill: "[pill]", diamond: "[diamond]", cylinder: "[cylinder]",
    hexagon: "⬡", parallelogram: "▱", document: "📄", triangle: "🔺",
  };
  return map[shape] ?? "[node]";
}
