/**
 * Cross-Engine SQL Export
 *
 * Translates the active ERD canvas state (table nodes + their column rows +
 * FK connection wires) into a download-ready SQL script targeting one of:
 *
 *   - PostgreSQL / Supabase  — clean SQL ready for the Supabase SQL Editor
 *   - MySQL / XAMPP MariaDB   — backtick-quoted, CONSTRAINT blocks, ENGINE=InnoDB
 *   - SQLite                 — inline constraints, primitive types only
 *
 * The exporter accepts a normalized ErdTable[] (produced by the ERD canvas
 * from the live node/edge state) and returns a string.
 */

import type { Cardinality } from "./sql-tokenizer";

export type ExportTarget = "postgresql" | "mysql" | "sqlite";

export interface ErdColumn {
  name: string;
  type: string; // universal primitive: INTEGER | TEXT | REAL | BLOB | BOOLEAN | TIMESTAMP | JSON | UUID | NUMERIC
  pk: boolean;
  fk: boolean;
  unique: boolean;
  nullable: boolean;
  referencesTable?: string;
  referencesColumn?: string;
}

export interface ErdTable {
  name: string;
  columns: ErdColumn[];
}

export interface ExportOptions {
  target: ExportTarget;
  /** include DROP TABLE IF EXISTS before each CREATE (idempotent re-runs) */
  includeDrops?: boolean;
}

// ─── Type translation per dialect ───────────────────────────────────────────

/**
 * Translate a universal primitive type to a dialect-specific type.
 */
function translateType(universal: string, target: ExportTarget): string {
  const u = universal.toUpperCase();

  if (target === "sqlite") {
    // SQLite only has 5 storage classes: INTEGER, TEXT, REAL, BLOB, NUMERIC
    switch (u) {
      case "INTEGER":
      case "BOOLEAN":
        return "INTEGER"; // SQLite stores booleans as 0/1 integers
      case "TEXT":
      case "JSON":
      case "UUID":
      case "TIMESTAMP":
        return "TEXT";
      case "REAL":
      case "NUMERIC":
        return "REAL";
      case "BLOB":
        return "BLOB";
      default:
        return "TEXT";
    }
  }

  if (target === "mysql") {
    switch (u) {
      case "INTEGER":
        return "INT";
      case "TEXT":
        return "TEXT";
      case "REAL":
        return "DOUBLE";
      case "NUMERIC":
        return "DECIMAL(10,2)";
      case "BLOB":
        return "LONGBLOB";
      case "BOOLEAN":
        return "TINYINT(1)";
      case "TIMESTAMP":
        return "DATETIME";
      case "JSON":
        return "JSON";
      case "UUID":
        return "CHAR(36)";
      default:
        return "TEXT";
    }
  }

  // postgresql / supabase
  switch (u) {
    case "INTEGER":
      return "INTEGER";
    case "TEXT":
      return "TEXT";
    case "REAL":
      return "REAL";
    case "NUMERIC":
      return "NUMERIC(10,2)";
    case "BLOB":
      return "BYTEA";
    case "BOOLEAN":
      return "BOOLEAN";
    case "TIMESTAMP":
      return "TIMESTAMPTZ";
    case "JSON":
      return "JSONB";
    case "UUID":
      return "UUID";
    default:
      return "TEXT";
  }
}

// ─── Identifier quoting ─────────────────────────────────────────────────────

function quote(name: string, target: ExportTarget): string {
  if (target === "mysql") return "`" + name + "`";
  if (target === "sqlite") return '"' + name + '"';
  return '"' + name + '"'; // postgresql
}

// ─── Per-target exporters ───────────────────────────────────────────────────

function exportPostgres(tables: ErdTable[], includeDrops: boolean): string {
  const lines: string[] = [];
  lines.push("-- Generated by Repodre — PostgreSQL / Supabase export");
  lines.push("-- Paste into the Supabase SQL Editor and run.");
  lines.push("");

  for (const table of tables) {
    if (includeDrops) {
      lines.push(`DROP TABLE IF EXISTS ${quote(table.name, "postgresql")} CASCADE;`);
    }
    lines.push(`CREATE TABLE ${quote(table.name, "postgresql")} (`);
    const colLines: string[] = [];
    for (const col of table.columns) {
      const type = translateType(col.type, "postgresql");
      let line = `  ${quote(col.name, "postgresql")} ${type}`;
      if (col.pk) line += " PRIMARY KEY";
      if (!col.nullable && !col.pk) line += " NOT NULL";
      if (col.unique && !col.pk) line += " UNIQUE";
      colLines.push(line);
    }
    // Inline FK constraints
    for (const col of table.columns) {
      if (col.fk && col.referencesTable && col.referencesColumn) {
        colLines.push(
          `  CONSTRAINT fk_${table.name}_${col.name} FOREIGN KEY (${quote(col.name, "postgresql")}) ` +
            `REFERENCES ${quote(col.referencesTable, "postgresql")} (${quote(col.referencesColumn, "postgresql")})`
        );
      }
    }
    lines.push(colLines.join(",\n"));
    lines.push(");");
    lines.push("");
  }

  return lines.join("\n");
}

function exportMysql(tables: ErdTable[], includeDrops: boolean): string {
  const lines: string[] = [];
  lines.push("-- Generated by Repodre — MySQL / XAMPP MariaDB export");
  lines.push("");
  lines.push("SET FOREIGN_KEY_CHECKS = 0;");
  lines.push("");

  for (const table of tables) {
    if (includeDrops) {
      lines.push(`DROP TABLE IF EXISTS ${quote(table.name, "mysql")};`);
    }
    lines.push(`CREATE TABLE ${quote(table.name, "mysql")} (`);
    const colLines: string[] = [];
    for (const col of table.columns) {
      const type = translateType(col.type, "mysql");
      let line = `  ${quote(col.name, "mysql")} ${type}`;
      if (col.pk) line += " AUTO_INCREMENT PRIMARY KEY";
      if (!col.nullable && !col.pk) line += " NOT NULL";
      if (col.unique && !col.pk) line += " UNIQUE";
      colLines.push(line);
    }
    // FK constraints as CONSTRAINT blocks
    for (const col of table.columns) {
      if (col.fk && col.referencesTable && col.referencesColumn) {
        colLines.push(
          `  CONSTRAINT \`fk_${table.name}_${col.name}\` FOREIGN KEY (${quote(col.name, "mysql")}) ` +
            `REFERENCES ${quote(col.referencesTable, "mysql")} (${quote(col.referencesColumn, "mysql")})`
        );
      }
    }
    lines.push(colLines.join(",\n"));
    lines.push(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");
    lines.push("");
  }

  lines.push("SET FOREIGN_KEY_CHECKS = 1;");
  return lines.join("\n");
}

function exportSqlite(tables: ErdTable[], includeDrops: boolean): string {
  const lines: string[] = [];
  lines.push("-- Generated by Repodre — SQLite export");
  lines.push("-- Types are stripped to SQLite primitives (INTEGER, TEXT, REAL, BLOB).");
  lines.push("");

  for (const table of tables) {
    if (includeDrops) {
      lines.push(`DROP TABLE IF EXISTS ${quote(table.name, "sqlite")};`);
    }
    lines.push(`CREATE TABLE ${quote(table.name, "sqlite")} (`);
    const colLines: string[] = [];
    for (const col of table.columns) {
      const type = translateType(col.type, "sqlite");
      let line = `  ${quote(col.name, "sqlite")} ${type}`;
      // SQLite: inline PRIMARY KEY + autoincrement for INTEGER PKs
      if (col.pk) {
        line += " PRIMARY KEY";
        if (col.type === "INTEGER") line += " AUTOINCREMENT";
      }
      if (!col.nullable && !col.pk) line += " NOT NULL";
      if (col.unique && !col.pk) line += " UNIQUE";
      // Inline REFERENCES for FK
      if (col.fk && col.referencesTable && col.referencesColumn) {
        line += ` REFERENCES ${quote(col.referencesTable, "sqlite")} (${quote(col.referencesColumn, "sqlite")})`;
      }
      colLines.push(line);
    }
    lines.push(colLines.join(",\n"));
    lines.push(");");
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Export a set of ERD tables to a SQL script for the given target dialect.
 */
export function exportSchema(
  tables: ErdTable[],
  options: ExportOptions
): string {
  const { target, includeDrops = true } = options;
  switch (target) {
    case "postgresql":
      return exportPostgres(tables, includeDrops);
    case "mysql":
      return exportMysql(tables, includeDrops);
    case "sqlite":
      return exportSqlite(tables, includeDrops);
  }
}

/**
 * Trigger a browser download of the exported schema as `schema_export.sql`.
 */
export function downloadSchema(sql: string, filename = "schema_export.sql"): void {
  const blob = new Blob([sql], { type: "text/sql" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Human-readable label for each export target (for the dropdown button).
 */
export const EXPORT_TARGET_LABELS: Record<ExportTarget, string> = {
  postgresql: "PostgreSQL / Supabase",
  mysql: "MySQL / XAMPP",
  sqlite: "SQLite",
};
